DROP TABLE IF EXISTS genders;
DROP TABLE IF EXISTS bowstyles;
DROP TABLE IF EXISTS ages;
DROP TABLE IF EXISTS rounds;

CREATE TABLE genders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  gender TEXT NOT NULL
);

CREATE TABLE bowstyles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bowstyle TEXT NOT NULL,
  disciplines TEXT NOT NULL
);

CREATE TABLE ages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  age_group TEXT NOT NULL,
  gov_body TEXT NOT NULL
);

CREATE TABLE rounds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
